const fs = require('fs')
const path = require('path')

module.exports = {
    name: 'html',
    alias: ['tohtml', 'text2html', 'webpage', 'txthtml'],
    category: 'Documents',
    desc: 'Convert text to simple.html document',
    usage: '.html <text> |.html <title> | <text>',

    execute: async (sock, m, { args, reply, prefix }) => {
        const BOT_NAME = process.env.BOT_NAME || 'XADON AI';
        try {
            let text = ''
            let customTitle = 'Text Document';

            // Get text from args
            if (args.length > 0) {
                const fullInput = args.join(' ');
                // Support:.html Title | Text here
                if (fullInput.includes('|')) {
                    const parts = fullInput.split('|').map(p => p.trim());
                    customTitle = parts[0];
                    text = parts.slice(1).join('|');
                } else {
                    text = fullInput;
                }
            }

            // Fallback to quoted message text
            if (!text && m.quoted) {
                text = (m.quoted.text || m.quoted.caption || '').trim()
            }

            if (!text) {
                let help = `✦ ───── ⋆⋅☆⋅⋆ ───── ✦
    ֎ • ${BOT_NAME} HTML GENERATOR •
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *TEXT TO HTML*
│ ❏ Usage : ${prefix}html <text>
│ ❏ With Title : ${prefix}html My Page | Hello World
│ ❏ Reply : Reply to text with ${prefix}html
│ ❏ Limit : 15000 characters
╰─────────────────────────╯`;
                return reply(help);
            }

            // Limit length
            if (text.length > 15000) {
                text = text.substring(0, 14997) + '...'
            }

            await reply('֎ Creating.html document...');

            // Basic HTML template with styling
            const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${customTitle} - ${BOT_NAME}</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #f8f9fa;
            color: #333;
            margin: 0;
            padding: 40px;
            line-height: 1.6;
        }
       .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        }
        h1 {
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
            text-align: center;
        }
        pre, code {
            background: #f1f1f1;
            padding: 15px;
            border-radius: 8px;
            overflow-x: auto;
            white-space: pre-wrap;
        }
       .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 0.9em;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>${customTitle}</h1>
        <pre>${text.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\n/g, '<br>')}</pre>
        <div class="footer">
            Generated by ${BOT_NAME} • ${new Date().toLocaleString('en-NG')}
        </div>
    </div>
</body>
</html>
            `

            const tempDir = path.join(__dirname, '../../temp')
            if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir, { recursive: true })

            const fileName = `${customTitle.replace(/\s/g, '_')}_${Date.now()}.html`
            const filePath = path.join(tempDir, fileName)

            fs.writeFileSync(filePath, htmlContent, 'utf8')

            const buffer = fs.readFileSync(filePath)
            const sizeKB = (buffer.length / 1024).toFixed(1);

            let caption = `✦ ───── ⋆⋅☆⋅⋆ ───── ✦
    ֎ • ${BOT_NAME} HTML FILE •
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *HTML CREATED*
│ ❏ Title : ${customTitle}
│ ❏ File : ${fileName}
│ ❏ Length : ${text.length} chars
│ ❏ Size : ${sizeKB} KB
│ ❏ Bot : ${BOT_NAME}
╰─────────────────────────╯`;

            await sock.sendMessage(m.chat, {
                document: buffer,
                mimetype: 'text/html',
                fileName: fileName,
                caption: caption
            }, { quoted: m })

            reply('֎ Sent as.html webpage! Tap to open in browser');

            // Cleanup
            fs.unlinkSync(filePath)

        } catch (e) {
            console.log('[HTML ERROR]', e.message)
            reply(`✘ ֎ Failed to create.html document\n❏ Error: ${e.message}`)
        }
    }
}