module.exports = {
  // AI
  newbg: "nature background",
  changebg: "beach sunset",
  deepseek: "tell me a joke",
  caption: "describe this image",
  gemini: "what is AI",
  gpt: "explain blockchain",
  horror: "scary story",
  imagine: "a dragon in space",
  pixelart: "pixel cat",
  story: "a boy who became king",
  weather: "Lagos",
  xm: "motivation quote",
  code: "create a login page",
  crysnova: "who are you",
  generate: "random idea",
  luna: "tell me something cool",
  remini: "enhance image",
  tojs: "convert python to js",

  // SEARCH
  fetchimage: "cars",
  fetchweb: "latest tech news",
  dict: "love",
  news: "Nigeria",
  sound: "rain",
  taxinfo: "USA tax",
  web: "OpenAI",
  esports: "latest tournaments",
  history: "World War 2",
  shazam: "identify song",
  wiki: "Elon Musk",

  // ADMIN
  kick: "@user",
  linkgc: "get link",
  listonline: "now",
  mute: "on",
  add: "234xxxxxxxxxx",
  antigm: "on",
  antilink: "on",
  antitag: "on",
  demote: "@user",
  events: "list",
  promote: "@user",
  tagall: "hello everyone",
  warn: "@user",
  setwelcome: "welcome message",

  // ANIME
  anime: "naruto",
  char: "luffy",
  "kill#": "@user",

  // AUDIO
  "8d": "audio",
  autosing: "song",
  deep: "audio",
  drunk: "audio",
  fast: "audio",
  bass: "audio",
  chipmunk: "audio",
  distort: "audio",
  echo: "audio",
  merge: "audio",
  nightcore: "audio",
  reverb: "audio",
  reverse: "audio",
  robot: "audio",
  slow: "audio",
  tremolo: "audio",

  // BOT (skip most simple ones)
  gitclone: "repo link",
  npm: "express",

  // CONVERTER
  lunav: "text",
  dec: "base64",
  ttp: "hello",
  tovn: "reply video",
  tovv: "reply audio",
  listvoice: "list",
  ttsm: "hello",
  tts: "hello",
  vv: "audio",
  vvcmd: "set",

  // DOCUMENTS
  doc: "file",
  html: "<h1>Hello</h1>",
  pdf: "text",
  scan: "image",
  txt: "text",
  zip: "files",
  word: "document",

  // DOWNLOADER
  apk: "whatsapp",
  bank: "bank name",
  fb: "https://facebook.com/...",
  mediafire: "link",
  pinterest: "design",
  play: "wizkid",
  spotify: "song name",
  tiktok: "link",
  video: "query",
  yt: "burna boy",
  yturld: "youtube link",
  d: "link",
  ing: "instagram link",

  // ECONOMY
  crypto: "btc",
  forex: "usd to naira",
  market: "stocks",
  economy: "Nigeria",

  // FUN
  jok: "random",
  meme: "funny",
  ascii: "cry",
  dice: "roll",
  emojimix: "😂+🔥",
  joke: "tell joke",
  quote: "motivation",
  reaction: "happy",
  "Crysnova!": "hi",

  // GROUP
  pin: "message",
  delgc: "confirm",
  glink: "get",
  hidetag: "hello",
  join: "link",
  leave: "bye",
  setgpp: "image",
  creategc: "group name",
  delgdesc: "clear",
  delgpp: "remove",
  gdesc: "new desc",
  getpp: "@user",
  gpp: "image",
  gcname: "new name",
  lockgc: "on",
  mutesticker: "on",
  muteuser: "@user",
  resetlink: "reset",
  tagadmin: "hello",
  unlockgc: "off",

  // MEDIA
  sticker: "reply image",
  togif: "reply sticker",
  toimg: "reply sticker",

  // MEDIA EDITOR
  brightness: "image",
  cyan: "image",
  glow: "image",
  gold: "image",
  gray: "image",
  green: "image",
  invert: "image",
  pixel: "image",
  purple: "image",
  red: "image",
  sparkle: "image",
  upscale: "image",
  xblur: "image",

  // OVERLAYS
  burial: "image",
  contrast: "image",
  jail: "image",
  rotate: "image",
  wanted: "image",

  // OWNER
  obf: "code",
  allvar: "list",
  anticall: "on",
  autoreact: "on",
  autoread: "on",
  delcmd: "name",
  delpp: "confirm",
  delvar: "var",
  deploy: "now",
  eval: "1+1",
  getvar: "BOT_NAME",
  mention: "@user",
  mode: "public",
  owner: "info",
  plugin: "install",
  reload: "now",
  restart: "now",
  setcmd: "cmd",
  setpp: "image",
  setvar: "key value",
  stats: "now",
  statusview: "on",
  sudo: "@user",
  uninstall: "plugin",
  x: "test",

  // TOOLS
  xfont: "hello",
  remind: "10m study",
  ss: "https://google.com",
  antidelete: "on",
  clearchat: "confirm",
  font: "hello",
  jid: "@user",
  readmore: "text",
  remcmd: "cmd",
  calculator: "2+2",
  setcrysai: "on",
  settrd: "on",
  short: "link",
  take: "sticker",
  tr: "hello",
  trd: "hello",

  // UTILS
  jidchannel: "link",
  tmd: "temp mail",
  url: "text",
  qr: "text",
  resize: "image",
  settmd: "on",
  sketcher: "image",
  tempemail: "create",
  nurl: "link",
  tm: "temp",
  sms24numbers: "get",
  sms24msg: "check",
  comic2: "image",
  rembg: "image"
};
