const axios = require('axios');
const BOT_NAME = process.env.BOT_NAME || 'XADON AI';

module.exports = {
    name: "brat",
    alias: ['brattext', 'bratmaker'],
    desc: 'Create a Brat-style image with text',
    category: "Maker",
    usage: ".brat <text>",
    examples: [".brat XADON", ".brat CODEX"],
    reactions: { start: '🎬', success: '✨', error: '✘' },

    execute: async (sock, m, { args, reply, prefix }) => {
        await sock.sendMessage(m.chat, { react: { text: '🎬', key: m.key } });

        const text = args.join(" ").trim();
        
        if (!text) {
            await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });
            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} BRAT MAKER*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *USAGE*
│ ❏ ${prefix}brat <text>
╰─────────────────────────╯
╭─֎ *EXAMPLE*
│ ❏ ${prefix}brat Boss
│ ❏ ${prefix}brat ${BOT_NAME}
╰─────────────────────────╯
_Powered by ${BOT_NAME}_`
            );
        }

        try {
            const response = await axios.get('https://api.zenzxz.my.id/maker/bratvid', {
                params: { text: text },
                responseType: 'arraybuffer',
                timeout: 30000
            });

            const contentType = response.headers['content-type'] || 'unknown';
            const buffer = Buffer.from(response.data);

            // Validate media
            const isValidMedia = (
                contentType.includes('image') ||
                contentType.includes('video') ||
                contentType.includes('octet-stream') ||
                contentType.includes('gif') ||
                buffer.slice(0, 6).toString() === 'GIF89a' ||
                buffer.slice(0, 8).toString('hex') === '89504e470d0a1a0a' ||
                buffer.slice(0, 3).toString('hex') === 'ffd8ff'
            );

            if (!isValidMedia) {
                await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });
                const errorText = buffer.toString().slice(0, 500);
                return reply(`✘ _API returned invalid data:_ ${errorText || 'Empty response'}`);
            }

            if (buffer.length < 100) {
                await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });
                return reply(`✘ _Media data too small or corrupted_ (${buffer.length} bytes)`);
            }

            await sock.sendMessage(m.chat, {
                image: buffer,
                caption: `🎬 _Brat: ${text}_\n_Generated by ${BOT_NAME}_`
            }, { quoted: m });

            await sock.sendMessage(m.chat, { react: { text: '✨', key: m.key } });

        } catch (error) {
            console.error(`[${BOT_NAME} BRAT ERROR]`, error.message);
            await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });
            
            if (error.code === 'ECONNABORTED') {
                return reply(`✘ _Request timed out. Try again._`);
            }
            if (error.response) {
                const status = error.response.status;
                const errorData = Buffer.from(error.response.data || '').toString().slice(0, 300);
                return reply(`✘ _API Error ${status}:_ ${errorData || 'Unknown error'}`);
            }
            if (error.request) {
                return reply(`✘ _No response from API. Service may be down._`);
            }
            return reply(`✘ _${error.message || 'Failed to create Brat image'}_`);
        }
    }
};