const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const { downloadContentFromMessage } = require('@whiskeysockets/baileys');
const BOT_NAME = process.env.BOT_NAME || 'XADON AI';

module.exports = {
    name: "rtoimg",
    alias: ['rtoimage', 'rtovideo', 'rtovid', 'r2img', 'round2img'],
    desc: 'Convert a round sticker back to image or video',
    category: "Media",
    usage: ".rtoimg",
    examples: [".rtoimg - reply to a round sticker"],
    reactions: { start: '🔄', success: '✨', error: '✘' },

    execute: async (sock, m, { reply, prefix }) => {
        await sock.sendMessage(m.chat, { react: { text: '🔄', key: m.key } });

        const quoted = m.quoted || m;
        const mime = (quoted.msg || quoted).mimetype || '';

        if (!/webp/.test(mime)) {
            await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });
            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} RTOIMG*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *USAGE*
│ ❏ Reply to a round sticker with ${prefix}rtoimg
╰─────────────────────────╯`
            );
        }

        try {
            const stream = await downloadContentFromMessage(quoted.msg || quoted, 'sticker');
            let buffer = Buffer.from([]);
            for await (const chunk of stream) {
                buffer = Buffer.concat([buffer, chunk]);
            }

            const isAnimated = buffer.toString('hex', 0, 16).includes('414e494d');

            const tempDir = path.join(__dirname, '../../temp');
            if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir, { recursive: true });

            const input = path.join(tempDir, `rtoimg_${Date.now()}.webp`);
            fs.writeFileSync(input, buffer);

            if (isAnimated) {
                // Animated round sticker → MP4 video
                const output = path.join(tempDir, `rtoimg_${Date.now()}.mp4`);
                
                const cmd = `ffmpeg -y -i "${input}" -c:v libx264 -pix_fmt yuv420p -preset fast -crf 23 -vf "format=yuv420p" "${output}"`;

                await new Promise((resolve, reject) => {
                    exec(cmd, (err) => {
                        if (err) reject(err);
                        else resolve();
                    });
                });

                const videoBuffer = fs.readFileSync(output);
                
                await sock.sendMessage(m.chat, {
                    video: videoBuffer,
                    caption: `🔄 _Round Sticker → Video_\n_Generated by ${BOT_NAME}_`
                }, { quoted: m });

                fs.unlinkSync(output);
            } else {
                // Static round sticker → PNG with transparency
                const output = path.join(tempDir, `rtoimg_${Date.now()}.png`);
                
                const cmd = `ffmpeg -y -i "${input}" "${output}"`;

                await new Promise((resolve, reject) => {
                    exec(cmd, (err) => {
                        if (err) reject(err);
                        else resolve();
                    });
                });

                const imageBuffer = fs.readFileSync(output);
                
                await sock.sendMessage(m.chat, {
                    image: imageBuffer,
                    caption: `🔄 _Round Sticker → Image_\n_Generated by ${BOT_NAME}_`
                }, { quoted: m });

                fs.unlinkSync(output);
            }

            fs.unlinkSync(input);
            await sock.sendMessage(m.chat, { react: { text: '✨', key: m.key } });

        } catch (err) {
            console.error(`[${BOT_NAME} RTOIMG ERROR]`, err.message);
            await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });
            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} RTOIMG*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *ERROR*
│ ❏ Failed to convert sticker
│ ❏ ${err.message}
╰─────────────────────────╯`
            );
        }
    }
};