const mumaker = require('mumaker');
const BOT_NAME = process.env.BOT_NAME || 'XADON AI';

module.exports = {
    name: "fire",
    alias: ['firetext', 'flame'],
    desc: 'Create a flame/fire text effect',
    category: "Textmaker",
    usage: ".fire <text>",
    examples: [".fire XADON", ".fire Boss"],
    reactions: { start: '🔥', success: '🧯', error: '✘' },

    execute: async (sock, m, { args, reply, prefix }) => {
        await sock.sendMessage(m.chat, { react: { text: '🔥', key: m.key } });

        const text = args.join(" ").trim();

        if (!text) {
            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} FIRE TEXT*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *USAGE*
│ ❏ ${prefix}fire <text>
╰─────────────────────────╯
╭─֎ *EXAMPLE*
│ ❏ ${prefix}fire Boss
╰─────────────────────────╯
_Powered by ${BOT_NAME}_`
            );
        }

        try {
            const result = await mumaker.ephoto('https://en.ephoto360.com/flame-lettering-effect-372.html', text);

            if (!result || !result.image) {
                throw new Error("No image URL received from the API");
            }

            await sock.sendMessage(m.chat, {
                image: { url: result.image },
                caption: `🔥 _Fire text: ${text}_\n_Generated by ${BOT_NAME}_`
            }, { quoted: m });

            await sock.sendMessage(m.chat, { react: { text: '🧯', key: m.key } });

        } catch (err) {
            console.error(`[${BOT_NAME} FIRE ERROR]`, err.message);
            await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });

            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} FIRE TEXT*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *ERROR*
│ ❏ Failed to generate
│ ❏ ${err.message}
╰─────────────────────────╯`
            );
        }
    }
};