const mumaker = require('mumaker');
const BOT_NAME = process.env.BOT_NAME || 'XADON AI';

module.exports = {
    name: "metallic",
    alias: ['metal', 'metaltext', '3dmetal'],
    desc: 'Create a decorative 3D metal text effect',
    category: "Textmaker",
    usage: ".metallic <text>",
    examples: [".metallic XADON", ".metallic Boss"],
    reactions: { start: '⚙️', success: '🪙', error: '✘' },

    execute: async (sock, m, { args, reply, prefix }) => {
        await sock.sendMessage(m.chat, { react: { text: '⚙️', key: m.key } });

        const text = args.join(" ").trim();

        if (!text) {
            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} METALLIC TEXT*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *USAGE*
│ ❏ ${prefix}metallic <text>
╰─────────────────────────╯
╭─֎ *EXAMPLE*
│ ❏ ${prefix}metallic Boss
╰─────────────────────────╯
_Powered by ${BOT_NAME}_`
            );
        }

        try {
            const result = await mumaker.ephoto('https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html', text);

            if (!result || !result.image) {
                throw new Error("No image URL received from the API");
            }

            await sock.sendMessage(m.chat, {
                image: { url: result.image },
                caption: `⚙️ _Metallic text: ${text}_\n_Generated by ${BOT_NAME}_`
            }, { quoted: m });

            await sock.sendMessage(m.chat, { react: { text: '🪙', key: m.key } });

        } catch (err) {
            console.error(`[${BOT_NAME} METALLIC ERROR]`, err.message);
            await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });

            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} METALLIC TEXT*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *ERROR*
│ ❏ Failed to generate
│ ❏ ${err.message}
╰─────────────────────────╯`
            );
        }
    }
};