const mumaker = require('mumaker');
const BOT_NAME = process.env.BOT_NAME || 'XADON AI';

module.exports = {
    name: "light",
    alias: ['lighttext', 'neonlight', 'futuristic'],
    desc: 'Create a futuristic light/neon text effect',
    category: "Textmaker",
    usage: ".light <text>",
    examples: [".light XADON", ".light Tech"],
    reactions: { start: '💡', success: '✨', error: '✘' },

    execute: async (sock, m, { args, reply, prefix }) => {
        await sock.sendMessage(m.chat, { react: { text: '💡', key: m.key } });

        const text = args.join(" ").trim();

        if (!text) {
            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} LIGHT TEXT*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *USAGE*
│ ❏ ${prefix}light <text>
╰─────────────────────────╯
╭─֎ *EXAMPLE*
│ ❏ ${prefix}light Boss
╰─────────────────────────╯
_Powered by ${BOT_NAME}_`
            );
        }

        try {
            const result = await mumaker.ephoto('https://en.ephoto360.com/light-text-effect-futuristic-technology-style-648.html', text);

            if (!result || !result.image) {
                throw new Error("No image URL received from the API");
            }

            await sock.sendMessage(m.chat, {
                image: { url: result.image },
                caption: `💡 _Light text: ${text}_\n_Generated by ${BOT_NAME}_`
            }, { quoted: m });

            await sock.sendMessage(m.chat, { react: { text: '✨', key: m.key } });

        } catch (err) {
            console.error(`[${BOT_NAME} LIGHT ERROR]`, err.message);
            await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });

            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} LIGHT TEXT*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *ERROR*
│ ❏ Failed to generate
│ ❏ ${err.message}
╰─────────────────────────╯`
            );
        }
    }
};