const fs = require('fs');
const path = require('path');
const BOT_NAME = process.env.BOT_NAME || 'XADON AI';

module.exports = [{
    name: 'chart',
    alias: ['graph', 'plot', 'bargraph', 'asciichart'],
    category: 'Documents',
    desc: 'Generate an ASCII bar chart',
    usage: '.chart Title | label1:value1 | label2:value2 | label3:value3',

    execute: async (sock, m, { args, reply, prefix }) => {
        const input = args.join(' ').trim();
        if (!input) {
            let help = `✦ ───── ⋆⋅☆⋅⋆ ───── ✦
    ֎ • ${BOT_NAME} CHART •
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *BAR CHART GENERATOR*
│ ❏ Usage : ${prefix}chart Title | A:10 | B:20
│ ❏ Example : ${prefix}chart Sales | Jan:100 | Feb:250
│ ❏ More : ${prefix}piechart | ${prefix}linechart
│ ❏ Max Bar : 20 blocks
╰─────────────────────────╯`;
            return reply(help);
        }

        const parts = input.split('|').map(p => p.trim());
        if (parts.length < 2) return reply('✘ ֎ Provide title and at least one data point');

        const title = parts[0];
        let maxVal = 0;
        const data = [];

        parts.slice(1).forEach(p => {
            const match = p.match(/^(.+):(\d+)$/);
            if (match) {
                const val = parseInt(match[2]);
                data.push({ label: match[1].trim(), value: val });
                if (val > maxVal) maxVal = val;
            }
        });

        if (!data.length) return reply('✘ ֎ No valid data found');

        const barWidth = 20;
        let chart = `✦ ───── ⋆⋅☆⋅⋆ ───── ✦
    ֎ • ${BOT_NAME} CHART •
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *${title.toUpperCase()}*
`;

        data.forEach(d => {
            const fill = Math.round((d.value / maxVal) * barWidth);
            const bar = '◉'.repeat(fill) + '◦'.repeat(barWidth - fill);
            chart += `│ ❏ ${d.label.padEnd(8)} : ${bar} ${d.value}\n`;
        });

        chart += `│
│ ❏ Generated by : ${BOT_NAME}
╰─────────────────────────╯`;

        const tempDir = path.join(__dirname, '../../temp');
        if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir, { recursive: true });
        const filePath = path.join(tempDir, `chart_${Date.now()}.txt`);
        fs.writeFileSync(filePath, chart);

        await sock.sendMessage(m.chat, {
            document: fs.readFileSync(filePath),
            fileName: `${title}_chart.txt`,
            mimetype: 'text/plain',
            caption: `✦ ───── ⋆⋅☆⋅⋆ ───── ✦
    ֎ • ${BOT_NAME} CHART •
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *DOCUMENT READY*
│ ❏ Type : Bar Chart
│ ❏ Title : ${title}
│ ❏ Points : ${data.length}
╰─────────────────────────╯`
        }, { quoted: m });

        fs.unlinkSync(filePath);
    }
},
// NEW SUBCOMMAND 1
{
    name: 'piechart',
    alias: ['pie'],
    category: 'Documents',
    desc: 'Generate ASCII pie chart',
    usage: '.piechart Title | label:value',
    execute: async (sock, m, { args, reply, prefix }) => {
        const input = args.join(' ').trim();
        if (!input) return reply(`✘ ֎ Usage: ${prefix}piechart Food | Rice:40 | Beans:30 | Meat:30`);

        const parts = input.split('|').map(p => p.trim());
        const title = parts[0];
        let total = 0;
        const data = [];

        parts.slice(1).forEach(p => {
            const match = p.match(/^(.+):(\d+)$/);
            if (match) {
                const val = parseInt(match[2]);
                data.push({ label: match[1].trim(), value: val });
                total += val;
            }
        });

        let chart = `✦ ───── ⋆⋅☆⋅⋆ ───── ✦
    ֎ • ${BOT_NAME} PIE CHART •
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *${title.toUpperCase()}*
`;
        data.forEach(d => {
            const percent = ((d.value / total) * 100).toFixed(1);
            const blocks = '✧'.repeat(Math.round(percent / 5));
            chart += `│ ❏ ${d.label} : ${percent}% ${blocks}\n`;
        });
        chart += `╰─────────────────────────╯`;
        reply(chart);
    }
},
// NEW SUBCOMMAND 2
{
    name: 'linechart',
    alias: ['line'],
    category: 'Documents',
    desc: 'Generate ASCII line chart',
    usage: '.linechart Title | label:value',
    execute: async (sock, m, { args, reply, prefix }) => {
        const input = args.join(' ').trim();
        if (!input) return reply(`✘ ֎ Usage: ${prefix}linechart Growth | Week1:10 | Week2:25 | Week3:40`);

        const parts = input.split('|').map(p => p.trim());
        const title = parts[0];
        const data = [];

        parts.slice(1).forEach(p => {
            const match = p.match(/^(.+):(\d+)$/);
            if (match) data.push({ label: match[1].trim(), value: parseInt(match[2]) });
        });

        let chart = `✦ ───── ⋆⋅☆⋅⋆ ───── ✦
    ֎ • ${BOT_NAME} LINE CHART •
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *${title.toUpperCase()}*
`;
        data.forEach(d => {
            chart += `│ ❏ ${d.label.padEnd(8)} : ${'★'.repeat(Math.min(d.value/5, 15))} ${d.value}\n`;
        });
        chart += `╰─────────────────────────╯`;
        reply(chart);
    }
}];