module.exports = {
    name: 'table',
    alias: ['tbl', 'grid', 'maketable'],
    category: 'Documents',
    desc: 'Generate a table in chat',
    usage: '.table Title | H1,H2,H3 | R1C1,R1C2,R1C3',

    execute: async (sock, m, { args, reply, prefix }) => {
        const BOT_NAME = process.env.BOT_NAME || 'XADON AI';
        const input = args.join(' ').trim();
        if (!input) {
            let help = `✦ ───── ⋆⋅☆⋅⋆ ───── ✦
    ֎ • ${BOT_NAME} TABLE MAKER •
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *TABLE GENERATOR*
│ ❏ Usage : ${prefix}table Title | col1,col2 | val1,val2
│ ❏ Example : ${prefix}table Users | Name,Age | John,25
│ ❏ Format : Title | Header | Row1 | Row2
│ ❏ Output : WhatsApp Native Table
╰─────────────────────────╯`;
            return reply(help);
        }

        const parts = input.split('|').map(p => p.trim());
        if (parts.length < 2) return reply('✘ ֎ Provide title and data rows');

        const title = parts[0];
        const rows = parts.slice(1);

        // Build table data for WhatsApp native table
        const tableData = [];
        let colCount = 0;
        
        rows.forEach((row, i) => {
            const cols = row.split(',').map(c => c.trim());
            if (i === 0) colCount = cols.length;
            tableData.push(cols);
        });

        try {
            await reply('֎ Generating table...');

            // WhatsApp native table
            await sock.sendMessage(m.chat, {
                headerText: `✦ ${title}`,
                contentText: '─'.repeat(20),
                title: `❏ ${rows.length} Row${rows.length > 1 ? 's' : ''} | ${colCount} Column${colCount > 1 ? 's' : ''}`,
                table: tableData,
                footerText: `֎ Generated by ${BOT_NAME}`
            }, { quoted: m });

            // Also send markdown preview for copy
            let md = `**${title}**\n\n`;
            tableData.forEach((r, i) => {
                md += `| ${r.join(' | ')} |\n`;
                if (i === 0) md += `|${' --- |'.repeat(r.length)}\n`;
            });
            await sock.sendMessage(m.chat, { text: `\`\`\`\n${md}\`\`\`` }, { quoted: m });

        } catch (e) {
            console.error('[TABLE]', e);
            reply(`✘ ֎ Failed to generate table\n❏ Error: ${e.message}`);
        }
    }
};