const fs = require('fs');
const path = require('path');
const { Packer, Document, Paragraph, TextRun, HeadingLevel } = require('docx');
const BOT_NAME = process.env.BOT_NAME || 'XADON AI';

module.exports = {
    name: 'word',
    alias: ['docx', 'toword', 'text2docx', 'doc'],
    category: 'Documents',
    desc: 'Convert text to.docx document',
    usage: '.word Title | Text\n.reply to text with.word',

    execute: async (sock, m, { args, reply, prefix }) => {
        try {
            let input = args.join(' ').trim();
            let text = '';
            let title = 'Document';

            // Get text from args
            if (input) {
                if (input.includes('|')) {
                    const parts = input.split('|').map(p => p.trim());
                    title = parts[0] || 'Document';
                    text = parts.slice(1).join(' | ');
                } else {
                    text = input;
                }
            }

            // Or fallback to quoted message text
            if (!text && m.quoted) {
                text = (m.quoted.text || m.quoted.caption || '').trim();
            }

            if (!text) {
                let help = `✦ ───── ⋆⋅☆⋅⋆ ───── ✦
    ֎ • ${BOT_NAME} WORD CREATOR •
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *DOCX GENERATOR*
│ ❏ With Title : ${prefix}word Title | Your text here
│ ❏ From Reply : Reply to text with ${prefix}word
│ ❏ Example : ${prefix}word Meeting Notes | Discussed project
│ ❏ Limit : 10000 characters
╰─────────────────────────╯`;
                return reply(help);
            }

            await reply('֎ Creating.docx document...');

            // Limit length for safety
            if (text.length > 10000) {
                text = text.substring(0, 9997) + '...';
            }

            // Create DOCX with proper formatting
            const doc = new Document({
                creator: BOT_NAME,
                title: title,
                description: `Generated by ${BOT_NAME}`,
                sections: [{
                    properties: {},
                    children: [
                        new Paragraph({
                            heading: HeadingLevel.HEADING_1,
                            children: [
                                new TextRun({
                                    text: title,
                                    bold: true,
                                    size: 32, // 16pt
                                    font: 'Arial'
                                })
                            ]
                        }),
                        new Paragraph({ text: '' }), // spacer
                       ...text.split('\n').map(line =>
                            new Paragraph({
                                children: [
                                    new TextRun({
                                        text: line,
                                        size: 24, // 12pt
                                        font: 'Arial'
                                    })
                                ]
                            })
                        ),
                        new Paragraph({ text: '' }),
                        new Paragraph({
                            children: [
                                new TextRun({
                                    text: `Generated by ${BOT_NAME} on ${new Date().toLocaleDateString()}`,
                                    size: 18, // 9pt
                                    italics: true,
                                    font: 'Arial'
                                })
                            ]
                        })
                    ]
                }]
            });

            // Generate buffer
            const buffer = await Packer.toBuffer(doc);
            const fileName = `${title.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.docx`;

            let caption = `✦ ───── ⋆⋅☆⋅⋆ ───── ✦
    ֎ • ${BOT_NAME} DOCX FILE •
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *WORD DOCUMENT*
│ ❏ Title : ${title}
│ ❏ Length : ${text.length} characters
│ ❏ File : ${fileName}
│ ❏ Format : Microsoft Word.docx
│ ❏ Bot : ${BOT_NAME}
╰─────────────────────────╯`;

            await sock.sendMessage(m.chat, {
                document: buffer,
                mimetype: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                fileName: fileName,
                caption: caption
            }, { quoted: m });

            await sock.sendMessage(m.chat, { react: { text: '📄', key: m.key } });

        } catch (e) {
            console.error('[WORD ERROR]', e);
            reply(`✘ ֎ Failed to create.docx document\n❏ Error: ${e.message}`);
        }
    }
};