const fs = require('fs');
const path = require('path');
const BOT_NAME = process.env.BOT_NAME || 'XADON AI';

module.exports = {
    name: 'xml',
    alias: ['xmlgen', 'xmlfile', 'toxml'],
    category: 'Documents',
    desc: 'Generate an XML file',
    usage: '.xml root | child:value | child2:value2\n.reply to json with.xml',

    execute: async (sock, m, { args, reply, prefix }) => {
        let input = args.join(' ').trim();
        let rootName = 'root';
        let dataParts = [];

        // Case 1: From quoted JSON
        if (!input && m.quoted) {
            try {
                const quotedText = (m.quoted.text || m.quoted.caption || '').trim();
                const obj = JSON.parse(quotedText);
                rootName = 'data';
                dataParts = Object.entries(obj).map(([k, v]) => `${k}:${v}`);
                await reply('֎ Converting JSON to XML...');
            } catch (e) {
                return reply('✘ ֎ Quoted message is not valid JSON');
            }
        }
        // Case 2: Manual input
        else if (input) {
            const parts = input.split('|').map(p => p.trim());
            rootName = parts[0] || 'root';
            dataParts = parts.slice(1);
            if (!/^[a-zA-Z_][a-zA-Z0-9_.-]*$/.test(rootName)) {
                return reply('✘ ֎ Invalid root name. Use letters, numbers, _ -.');
            }
            await reply('֎ Generating XML file...');
        } else {
            let help = `✦ ───── ⋆⋅☆⋅⋆ ───── ✦
    ֎ • ${BOT_NAME} XML GENERATOR •
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *XML CREATOR*
│ ❏ Manual : ${prefix}xml root | key:value | key2:value2
│ ❏ From JSON : Reply to JSON with ${prefix}xml
│ ❏ Example : ${prefix}xml user | name:John | age:25
│ ❏ Output :.xml file
╰─────────────────────────╯`;
            return reply(help);
        }

        try {
            // Escape XML special chars
            const escapeXml = (unsafe) => {
                return unsafe.toString()
                   .replace(/&/g, "&amp;")
                   .replace(/</g, "&lt;")
                   .replace(/>/g, "&gt;")
                   .replace(/"/g, "&quot;")
                   .replace(/'/g, "&apos;");
            };

            let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
            xml += `<!-- Generated by ${BOT_NAME} -->\n`;
            xml += `<${rootName}>\n`;

            let tagCount = 0;
            dataParts.forEach(pair => {
                const match = pair.match(/^(\w+):(.+)$/);
                if (match) {
                    const key = match[1].trim();
                    const value = escapeXml(match[2].trim());
                    if (/^[a-zA-Z_][a-zA-Z0-9_.-]*$/.test(key)) {
                        xml += ` <${key}>${value}</${key}>\n`;
                        tagCount++;
                    }
                }
            });

            xml += `</${rootName}>`;

            const tempDir = path.join(__dirname, '../../temp');
            if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir, { recursive: true });
            const fileName = `${rootName}_${Date.now()}.xml`;
            const filePath = path.join(tempDir, fileName);
            fs.writeFileSync(filePath, xml, 'utf8');

            const sizeKB = (Buffer.byteLength(xml, 'utf8') / 1024).toFixed(1);

            let caption = `✦ ───── ⋆⋅☆⋅⋆ ───── ✦
    ֎ • ${BOT_NAME} XML FILE •
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *XML CREATED*
│ ❏ Root : <${rootName}>
│ ❏ Tags : ${tagCount}
│ ❏ File : ${fileName}
│ ❏ Size : ${sizeKB} KB
│ ❏ Encoding : UTF-8
│ ❏ Bot : ${BOT_NAME}
╰─────────────────────────╯`;

            await sock.sendMessage(m.chat, {
                document: fs.readFileSync(filePath),
                fileName: fileName,
                mimetype: 'application/xml',
                caption: caption
            }, { quoted: m });

            fs.unlinkSync(filePath);
            await sock.sendMessage(m.chat, { react: { text: '📋', key: m.key } });

        } catch (e) {
            console.error('[XML]', e);
            reply(`✘ ֎ Failed to create XML\n❏ Error: ${e.message}`);
        }
    }
};