const { applyEffect } = require("../Core/,*.js");
const BOT_NAME = process.env.BOT_NAME || 'XADON AI';

module.exports = {
    name: "brightness",
    alias: ["bright"],
    desc: 'Adjust image brightness',
    category: "Editor",
    usage: ".brightness <level>",
    examples: [".brightness 50 - reply to an image", ".bright -50 - reply to an image"],
    reactions: { start: '✨', success: '✅', error: '✘' },

    execute: async (sock, m, { args, reply, prefix }) => {
        await sock.sendMessage(m.chat, { react: { text: '✨', key: m.key } });

        if (!m.quoted) {
            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} BRIGHTNESS EDITOR*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *USAGE*
│ ❏ Reply to an image with ${prefix}brightness <level>
╰─────────────────────────╯
╭─֎ *EXAMPLE*
│ ❏ ${prefix}brightness 50
│ ❏ ${prefix}bright -30
╰─────────────────────────╯
_Note: Level from -100 to 100. Positive = brighter, Negative = darker_`
            );
        }

        if (!m.quoted.mtype?.includes("image")) {
            await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });
            return reply(`✘ _Reply to an image only_`);
        }

        try {
            const level = args[0] || "50"; // default 50 if no arg
            const buffer = await m.quoted.download();
            const result = await applyEffect(buffer, "brightness", [level]);

            await sock.sendMessage(m.chat, {
                image: result,
                mimetype: "image/png",
                caption: `✨ _Brightness: ${level}_\n_Generated by ${BOT_NAME}_`
            }, { quoted: m });

            await sock.sendMessage(m.chat, { react: { text: '✅', key: m.key } });

        } catch (err) {
            console.error(`[${BOT_NAME} BRIGHTNESS ERROR]`, err.message);
            await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });
            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} BRIGHTNESS EDITOR*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *ERROR*
│ ❏ Failed to edit image
│ ❏ ${err.message}
╰─────────────────────────╯`
            );
        }
    }
};