const mumaker = require('mumaker');
const BOT_NAME = process.env.BOT_NAME || 'XADON AI';

module.exports = {
    name: "sand",
    alias: ['sandtext', 'beach'],
    desc: 'Create a sand/beach writing text effect',
    category: "Textmaker",
    usage: ".sand <text>",
    examples: [".sand XADON", ".sand Summer 2026"],
    reactions: { start: '🏖️', success: '🏝️', error: '✘' },

    execute: async (sock, m, { args, reply, prefix }) => {
        await sock.sendMessage(m.chat, { react: { text: '🏖️', key: m.key } });

        const text = args.join(" ").trim();

        if (!text) {
            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} SAND TEXT*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *USAGE*
│ ❏ ${prefix}sand <text>
╰─────────────────────────╯
╭─֎ *EXAMPLE*
│ ❏ ${prefix}sand Boss
╰─────────────────────────╯
_Powered by ${BOT_NAME}_`
            );
        }

        try {
            const result = await mumaker.ephoto('https://en.ephoto360.com/write-names-and-messages-on-the-sand-online-582.html', text);

            if (!result || !result.image) {
                throw new Error("No image URL received from the API");
            }

            await sock.sendMessage(m.chat, {
                image: { url: result.image },
                caption: `🏖️ _Sand text: ${text}_\n_Generated by ${BOT_NAME}_`
            }, { quoted: m });

            await sock.sendMessage(m.chat, { react: { text: '🏝️', key: m.key } });

        } catch (err) {
            console.error(`[${BOT_NAME} SAND ERROR]`, err.message);
            await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });

            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} SAND TEXT*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *ERROR*
│ ❏ Failed to generate
│ ❏ ${err.message}
╰─────────────────────────╯`
            );
        }
    }
};