const mumaker = require('mumaker');
const BOT_NAME = process.env.BOT_NAME || 'XADON AI';

module.exports = {
    name: "arena",
    alias: ['arenatext', 'aov', 'valor'],
    desc: 'Create an Arena of Valor style text effect',
    category: "Textmaker",
    usage: ".arena <text>",
    examples: [".arena XADON", ".arena MVP"],
    reactions: { start: '🎬', success: '✨', error: '✘' },

    execute: async (sock, m, { args, reply, prefix }) => {
        await sock.sendMessage(m.chat, { react: { text: '🎬', key: m.key } });

        const text = args.join(" ").trim();

        if (!text) {
            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} ARENA TEXT*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *USAGE*
│ ❏ ${prefix}arena <text>
╰─────────────────────────╯
╭─֎ *EXAMPLE*
│ ❏ ${prefix}arena Boss
╰─────────────────────────╯
_Powered by ${BOT_NAME}_`
            );
        }

        try {
            const result = await mumaker.ephoto('https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html', text);

            if (!result || !result.image) {
                throw new Error("No image URL received from the API");
            }

            await sock.sendMessage(m.chat, {
                image: { url: result.image },
                caption: `🎬 _Arena of Valor text: ${text}_\n_Generated by ${BOT_NAME}_`
            }, { quoted: m });

            await sock.sendMessage(m.chat, { react: { text: '✨', key: m.key } });

        } catch (err) {
            console.error(`[${BOT_NAME} ARENA ERROR]`, err.message);
            await sock.sendMessage(m.chat, { react: { text: '✘', key: m.key } });

            return reply(
`✦ ───── ⋆⋅☆⋅⋆ ───── ✦
 ֎ *${BOT_NAME} ARENA TEXT*
✦ ───── ⋆⋅☆⋅⋆ ───── ✦
╭─֎ *ERROR*
│ ❏ Failed to generate
│ ❏ ${err.message}
╰─────────────────────────╯`
            );
        }
    }
};