const games=new Map();
const files='abcdefgh';
const back=['R','N','B','Q','K','B','N','R'];
function start(){const b=Array.from({length:8},()=>Array(8).fill(''));b[0]=back.map(x=>x.toLowerCase());b[1]=Array(8).fill('p');b[6]=Array(8).fill('P');b[7]=back;return b;}
function board(b){return b.map((r,i)=>`${8-i} ${r.map(x=>x||'·').join(' ')}`).join('\n')+'\n  a b c d e f g h';}
function pos(s){if(!/^[a-h][1-8]$/.test(s))return null;return [8-Number(s[1]),files.indexOf(s[0])];}
function clearPath(b,a,c,dr,dc){let r=a[0]+dr,cc=a[1]+dc;while(r!==c[0]||cc!==c[1]){if(b[r][cc])return false;r+=dr;cc+=dc;}return true;}
function legal(b,a,c){const p=b[a[0]][a[1]],q=b[c[0]][c[1]];if(!p||p===q||p.toLowerCase()===q?.toLowerCase()&&q)return false;const dr=c[0]-a[0],dc=c[1]-a[1],adr=Math.abs(dr),adc=Math.abs(dc),type=p.toLowerCase();if(type==='p'){const dir=p==='P'?-1:1;const startRow=p==='P'?6:1;if(dc===0&&!q&&dr===dir)return true;if(dc===0&&!q&&a[0]===startRow&&dr===2*dir&&!b[a[0]+dir][a[1]])return true;return(adc===1&&dr===dir&&!!q)}if(type==='n')return(adr===2&&adc===1)||(adr===1&&adc===2);if(type==='k')return adr<=1&&adc<=1; if(type==='b'&&adr===adc)return clearPath(b,a,c,Math.sign(dr),Math.sign(dc));if(type==='r'&&(dr===0||dc===0))return clearPath(b,a,c,Math.sign(dr),Math.sign(dc));if(type==='q'&&(dr===0||dc===0||adr===adc))return clearPath(b,a,c,Math.sign(dr),Math.sign(dc));return false;}
module.exports={name:'chess',alias:['chessboard'],category:'Games',desc:'Dependency-free lightweight chess board with basic piece movement',usage:'.chess | .chess e2 e4',execute:async(sock,m,{args,reply})=>{const key=m.chat;let g=games.get(key);if(!g){g={b:start(),turn:'P'};games.set(key,g);return reply(`♟️ *Chess*\\n${board(g.b)}\\n\\nWhite moves first. Use .chess e2 e4`)}if(args.length===0)return reply(board(g.b));if(args[0].toLowerCase()==='reset'){games.delete(key);return reply('♻️ Chess board reset. Use .chess to start again.')}if(args.length<2)return reply('Usage: .chess e2 e4');const a=pos(args[0].toLowerCase()),c=pos(args[1].toLowerCase());if(!a||!c)return reply('Use coordinates such as e2 e4.');const p=g.b[a[0]][a[1]];if(!p)return reply('No piece on that square.');if((p===p.toUpperCase())!==(g.turn==='P'))return reply(`It is ${g.turn==='P'?'White':'Black'}'s turn.`);if(!legal(g.b,a,c))return reply('That basic piece move is not legal.');g.b[c[0]][c[1]]=p;g.b[a[0]][a[1]]='';g.turn=g.turn==='P'?'p':'P';return reply(`${board(g.b)}\\n\\nNext: ${g.turn==='P'?'White':'Black'}`)}};
